import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import ParticlesComponent from "./Components/ParticlesComponent/ParticlesComponent";
import Navbar from "./Components/Navbar/Navbar";
import Pagetransition from "./Components/Pagetransition/Pagetransition";
import StairTransition from "./Components/StairTransition/StairTransition";

const inter = Source_Code_Pro({ subsets: ["vietnamese"] ,weight:["900", "800", "700", "600", "500", "200"] });

export const metadata = {
  title: "Khan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Pagetransition>{children}</Pagetransition>
        <ParticlesComponent />
        <StairTransition />
      </body>
    </html>
  );
}
